version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    ports:
      - 8000:8000

volumes:
  db_data:
